---
title: "PSY505: Advances in Statistical Methods and Research Practices in Psychology"
subtitle:
excerpt: "Graduate-level coure course taught in [Fall 2022](https://psy505.netlify.app/), [Spring 2023](https://psy505-spring2023.netlify.app/schedule), [Fall 2023](https://psy505-fall2023.netlify.app/), [Spring 2024](https://psy505-s24.netlify.app/). This seminar introduces graduate students to methods and research practivces by having guest speakers from all over the world give talks. We have had Daniel Lakens, Deb Mayo, Bob Calin-Jageman, Paul Brukner, Chelsea Parlett-Pelleriti, Erin Buchanon, Patrick Curran, Greg Hancock, Amanda Montoya, and many others" 

author: "Dr. Jason Geller"
slug: class-psy-statistics-505
draft: false
tags:
  - Statistics
  - Open Materials
categories:
  - teaching
layout: single
links:
- icon: web
  icon_pack: fas
  name: Fall 2022
  url: https://https://psy505.netlify.app/
- icon: web
  icon_pack: fas
  name: Spring 2023
  url: https://psy505-spring2023.netlify.app/schedule
- icon: web
  icon_pack: fas
  name: Fall 2023
  url: https://psy505-fall2023.netlify.app/
- icon: web
  icon_pack: fas
  name: Spring 2024
  url: https://psy505-fall2023.netlify.app/

---

## About the course  

Psychological methods keep evolving: psychology researchers constantly adopt new statistical
methods, computational tools, and research practices. This course introduces the latest advances
in research methods in psychological science through a series of lectures, tutorials, and seminars. Lectures are generally given by a guest speaker who introduces methodological and statistical issues relevant to psychology research. Students engage in a group discussion with the speaker before the lecture. Tutorials provide students with the necessary skills to build reproducible and transparent research programs. For instance, students learn how to use R, RMarkdown and Git/GitHub, or how to preregister their studies. Finally, students take part in seminars,
in which they discuss timely topics in psychological methods (e.g., reproducibility, transparency,
pre-registration).


