---
title: "Measuring the semantic priming effect across many languages"
date: '2026-01-06'
author:
  - name: Erin M. Buchanan
  - name: Jason Geller
  - name: Et al
pub-info:
  reference: "Buchanan, E. M., Cuccolo, K., Heyman, T., van Berkel, N., Coles, N. A., Iyer, A., Peters, K., van 't Veer, A. E., Montefinese, M., Maxwell, N. P., Taylor, J. E., Valentine, K. D., Arriaga, P., Barzykowski, K., Boucher, L., Collins, W. M., Vaidis, D. C., Aczel, B., Al-Hoorie, A. H., ...<strong>Geller, J.</strong>, ... Lewis, S. C. (2026). Measuring the semantic priming effect across many languages. <em>Nature Human Behaviour</em>, <em>10</em>(1), 182–201. https://doi.org/10.1038/s41562-025-02254-x"
links:
    - name: Paper
      url: https://www.nature.com/articles/s41562-025-02254-x
      icon: fa-solid fa-scroll
    - name: Preprint
      url: https://reff.f.bg.ac.rs/bitstream/handle/123456789/6432/SPAML_RR_NHB_V4.pdf?sequence=1&isAllowed=y
      icon: ai ai-psyarxiv
    - name: OSF
      url: https://osf.io/wrpj4/?view_only=
      icon: ai ai-osf-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1038/s41562-025-02254-x
      icon: ai ai-zotero-square
doi: https://doi.org/10.1038/s41562-025-02254-x
---

## Abstract

Semantic priming has been studied for nearly 50 years across various experimental manipulations and theoretical frameworks. These studies provide insight into the cognitive underpinnings of semantic representations in both healthy and clinical populations; however, they have suffered from several issues including generally low sample sizes and a lack of diversity in linguistic implementations. Here, we will test the size and the variability of the semantic priming effect across ten languages by creating a large database of semantic priming values, based on an adaptive sampling procedure. Differences in response latencies between related word-pair conditions and unrelated word-pair conditions (i.e., difference score confidence interval is greater than zero) will allow quantifying evidence for semantic priming, whereas improvements in model fit with the addition of a random intercept for language will provide support for variability in semantic priming across languages.