---
title: "Sans Forgetica is not desirable for learning"
date: 2020-05-28
author:
  - name: Jason Geller
    affiliation: University of Alabama-Birmingham
  - name: Sara Davis
    affiliation: Skidmore University
  - name: Daniel Peterson 
    affiliation: Skidmore University
categories: 
  - Learning and Memory
  - Disfluency
  - Fonts
pub-info:
  reference: "<strong>Geller, J</strong>., Davis, S. D., & Peterson, D. J. (2020). Sans Forgetica is not desirable for learning. <em>Memory<em>, 28(8), 957–967. https://doi.org/10.1080/09658211.2020.1797096"
  links:
    - name: Final version
      url: https://www.tandfonline.com/doi/full/10.1080/09658211.2020.1797096
      icon: fa-solid fa-scroll
    - name: Preprint
      url: https://osf.io/preprints/psyarxiv/ku5bz
      icon: ai ai-psyarxiv
    - name: Preregistration 1
      url: https://osf.io/pk3zc
      icon: fa-solid fa-file
    - name: Preregistration 2
      url: https://osf.io/32nmg
      icon: fa-solid fa-file
    - name: OSF
      url: https://osf.io/d2vy8/
      icon: ai ai-osf-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1080/09658211.2020.1797096
      icon: ai ai-zotero-square
doi: https://doi.org/10.1080/09658211.2020.1797096
---

## Abstract

Do students learn better with material that is perceptually hard to process? While evidence is mixed, recent claims suggest that placing materials in Sans Forgetica, a perceptually difficult-to-process typeface, has positive impacts on student learning. Given the weak evidence for other similar perceptual disfluency effects, we examined the mnemonic effects of Sans Forgetica more closely in comparison to other learning strategies across three preregistered experiments. In Experiment 1, participants studied weakly related cue-target pairs with targets presented in either Sans Forgetica or with missing letters (e.g., cue: G_RL, the generation effect). Cued recall performance showed a robust effect of generation, but no Sans Forgetica memory benefit. In Experiment 2, participants read an educational passage about ground water with select sentences presented in either Sans Forgetica typeface, yellow pre-highlighting, or unmodified. Cued recall for select words was better for pre-highlighted information than an unmodified pure reading condition. Critically, presenting sentences in Sans Forgetica did not elevate cued recall compared to an unmodified pure reading condition or a pre-highlighted condition. In Experiment 3, individuals did not have better discriminability for Sans Forgetica relative to a fluent condition in an old-new recognition test. Our findings suggest that Sans Forgetica really is forgettable.
