---
title: "Improving Webcam Eye-Tracking: Impact of Hardware and Head Stabilization on Data Quality"
date: 2026-05-17

author:
  - name: Jason Geller
    affiliation: Boston College
  - name: João Veríssimo
    affiliation: University of Lisbon
  - name: Julia R. Drouin
    affiliation: University of North Carolina at Chapel Hill

categories:
  - Webcam eye-tracking
  - Spoken word recognition
  - VWP
  - Lab

pub-info:
  reference: >
    <strong>Geller, J.</strong>, Veríssimo, J., & Drouin, J. R. (2026).
    Improving Webcam Eye-Tracking: Impact of Hardware and Head Stabilization
    on Data Quality [Stage 1 Registered Report accepted in principle].
    <em>Behavioral Research Methods</em>.

  links:
    - name: Preprint
      url: https://osf.io/9jmz2
      icon: ai ai-psyarxiv-square

    - name: OSF
      url: https://osf.io/cf6xr/overview
      icon: ai ai-osf-square

    - name: Github
      url: https://github.com/jgeller112/Webcam2Lab-VWP
      icon: fa-brands fa-github-square
---

Abstract

Webcam-based eye-tracking offers a scalable and accessible alternative to traditional lab-based systems. While recent studies demonstrate that webcam eye-tracking can replicate canonical effects across domains such as language, memory, and decision-making, questions remain about its precision and reliability. In particular, spatial accuracy, temporal resolution, and attrition rates are often poorer than those observed with research-grade systems, raising the possibility that environmental and hardware factors introduce substantial noise. The present registered report directly tests two factors that may introduce noise into webcam data: camera quality and head stabilization. In Experiment 1, we examine the effect of external webcam quality (high vs. standard) in a single word Visual World Paradigm (VWP) task, testing whether using a better webcam can yield stronger competition effects, earlier effect onsets, and reduced attrition. In Experiment 2, we assess the impact of head stabilization (chin rest vs. no chin rest) under identical environmental conditions. Together, these studies identify the impact of hardware and movement on webcam eye-tracking data quality. Results will inform a more methodological understanding of webcam-based eye-tracking, clarifying whether its current limitations are intrinsic to the technology or can be mitigated through improved hardware and experimental control. These set of studies have implications for both online and in-lab utilization of webcam eye-tracking.

