---
title: "Multidimensional Signals and Analytic Flexibility: Estimating Degrees of Freedom in Human-Speech Analyses"
date: 2023-07-20
author:
  - name: Stefano Coretta 
  - name: Joseph V. Casillas
  - name: Timo B. Roettger
  - name: Jason Geller
categories: 
  - crowdsourcing science 
  - data analysis
  - scientific transparency
  -  speech
  - acoustic analysis
 
pub-info:
  reference: "Coretta, S., Casillas, J. V., Roessig, S., <strong>Geller, J</strong>., et al. (2023). Multidimensional signals and analytic flexibility: Estimating degrees of freedom in human-speech analyses. Advances in Methods and Practices in Psychological Science, 6(3). https://doi.org/10.1177/25152459231162567"
  links:
    - name: Final version
      url: https://journals.sagepub.com/doi/pdf/10.1177/25152459231162567
      icon: fa-solid fa-scroll
    - name: OSF
      url: https://osf.io/3bmcp/
      icon: fa-solid fa-table
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/25152459231162567
      icon: ai ai-zotero
doi: https://doi.org/10.1177/2515245923116256
---

## Abstract

Recent empirical studies have highlighted the large degree of analytic flexibility in data analysis that can lead to substantially different conclusions based on the same data set. Thus, researchers have expressed their concerns that these researcher degrees of freedom might facilitate bias and can lead to claims that do not stand the test of time. Even greater flexibility is to be expected in fields in which the primary data lend themselves to a variety of possible operationalizations. The multidimensional, temporally extended nature of speech constitutes an ideal testing ground for assessing the variability in analytic approaches, which derives not only from aspects of statistical modeling but also from decisions regarding the quantification of the measured behavior. In this study, we gave the same speech-production data set to 46 teams of researchers and asked them to answer the same research question, resulting in substantial variability in reported effect sizes and their interpretation. Using Bayesian meta-analytic tools, we further found little to no evidence that the observed variability can be explained by analysts’ prior beliefs, expertise, or the perceived quality of their analyses. In light of this idiosyncratic variability, we recommend that researchers more transparently share details of their analysis, strengthen the link between theoretical construct and quantitative system, and calibrate their (un)certainty in their conclusions.
