---
title: "This Is Not the ex-Gaussian Model You Are Looking For: On the Default Parameterization of Bayesian ex-Gaussian Models in brms"
date: 2026-01-30
author:
  - name: Jason Geller
    affiliation: Boston College
  - name: Bernhard Angele
    affiliation: Nebrija University
  - name: Dominique Makowski
    affiliation: University of Sussex

categories: 
    - reproducibility, 
    - ex-Gaussian
    - Bayesian estimation
    - brms
    - parameterization
    - R
pub-info:
  reference: "Geller, J., Angele, B., & Makowski, D. (2026). This Is Not the ex-Gaussian Model You Are Looking For: On the Default Parameterization of Bayesian ex-Gaussian Models in brms. Retrieved from osf.io/preprints/psyarxiv/kdcxa_v2"
  links:
    - name: Preprint
      url: https://osf.io/preprints/psyarxiv/kdcxa_v2
      icon: ai ai-psyarxiv-square

    - name: Commentary
      url: https://jgeller112.github.io/exGauss_commentary/
      icon: fa-solid fa-comment

    - name: Github
      url: https://github.com/jgeller112/exGauss_commentary
      icon: fa-brands fa-github-square

doi: https://doi.org/10.31234/osf.io/kdcxa
---

# Abstract

The ex-Gaussian distribution is a popular mathematical model for analyzing response time (RT) data because it separates the central portion of the distribution, captured by the Gaussian parameters $\mu$ and $\sigma$, from the positively skewed tail, captured by the exponential parameter $\tau$. Researchers often use these parameters to make inferences about underlying cognitive processes. As Bayesian methods have become increasingly accessible, complex ex-Gaussian models can now be fit with relative ease, and in R, the {brms} package makes this especially straightforward. However, it is important to recognize that the default parameterization offered by {brms} does not map onto the classical parameterization familiar to many researchers in experimental psychology: in the default model, $\mu$ indexes the mean of the full ex-Gaussian distribution rather than the location of the Gaussian component alone. This distinction matters because changes in the Gaussian location and changes in the exponential tail can offset one another at the level of the overall mean, so some published studies may have drawn incorrect inferences from effects estimated on the default $\mu$ parameter. Using simulated data and a published finding we highlight how using the default parameterization can lead to misleading inferences. We then demonstrate how to fit the classical parameterization directly using the {cogmod} package, with the aim of helping researchers and reviewers align ex-Gaussian model parameters with their theoretical questions.
