---
title: "Instructor fluency leads to higher confidence in learning, but not better learning"
date: 2018-04-29
author:
  - name: Alexander R. Toftenss
    affiliation: Iowa State University
  - name: Shana K. Carpenter
    affiliation: Iowa State University
  - name: Jason Geller
    affiliation: Iowa State University
  - name: Sierra Lauber
    affiliation: Iowa State University
  - name: Madeline Johnson
    affiliation: Iowa State University
  - name: Patrick I. Armstrong
    affiliation: Iowa State University
categories: 
  - Learning and Memory
  - Fluencuy
  - Disfluency
  - Metacognition
pub-info:
  reference: "Toftness, A. R., Carpenter, S. K., <strong>Geller, J</strong>., Lauber, S., Johnson, M., & Armstrong, P. I. (2018). Instructor fluency leads to higher confidence in learning, but not better learning. Metacognition and Learning, 13(1), 1–14. https://doi.org/10.1007/s11409-017-9175-0"
  links:
    - name: Final version
      url: https://doi.org/10.1007/s11409-017-9175-0
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1007/s11409-017-9175-0
      icon: ai ai-zotero
doi: https://doi.org/10.1007/s11409-017-9175-0
---

## Abstract

Students’ judgements of their own learning often exceed their knowledge on a given topic. One source of this pervasive overconfidence is fluency, the perceived ease with which information is acquired. Though effects of fluency on metacognitive judgments have been explored by manipulating relatively simple stimuli such as font style, few studies have explored the effects of fluency on more complex forms of learning encountered in educational settings, such as learning from lectures. The present study manipulated the fluency of a 31-min video-recorded lecture, and measured its effects on both perceived and actual learning. In the fluent condition, the instructor used non-verbal gestures, voice dynamics, mobility about the space, and appropriate pauses. In the disfluent condition, the same instructor read directly from notes, hunched over a podium, rarely made eye contact, used few non-verbal gestures, spoke in monotone pitch, and took irregular and awkward pauses. Though participants rated the fluent instructor significantly higher than the disfluent instructor on measures of teaching effectiveness and estimated that they had learned more of the material, actual learning between the two groups did not differ as assessed by a memory test over the lecture contents given immediately (Experiment 1) or after a 1-day delay (Experiment 2). This counterintuitive result reveals an “illusion of learning” due to fluency in lecture-based learning, a very common form of instruction.
