---
title: "Eyes wide open: Pupil size as a proxy for inhibition in the masked-priming paradigm"
date: 2016-05-20
author:
  - name: Jason Geller
    url: https://www.drjasongeller.com
    affiliation: Iowa State University
  - name: Mary L Still
    affiliation: Old Dominion University
  - name: Alison Morris
    affiliation: Iowa State University
categories: 
  - Pupillometry
  - Word Recognition
  - Language
  - Eye-tracking
  - Inhibition
pub-info:
  reference: "Geller, J., Still, M. L., & Morris, A. L. (2016). Eyes wide open: Pupil size as a proxy for inhibition in the masked-priming paradigm.*Memory & cognition*, 44(4), 554–564. https://doi.org/10.3758/s13421-015-0577-4"
  links:
    - name: Final version
      url: https://doi.org/10.3758/s13421-015-0577-
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.3758/s13421-015-0577-4
      icon: ai ai-zotero
doi: 10.3758/s13421-015-0577-4
---

## Abstract

A core assumption underlying competitive-network models of word recognition is that in order for a word to be recognized, the representations of competing orthographically similar words must be inhibited. This inhibitory mechanism is revealed in the masked-priming lexical-decision task (LDT) when responses to orthographically similar word prime–target pairs are slower than orthographically different word prime–target pairs (i.e., inhibitory priming). In English, however, behavioral evidence for inhibitory priming has been mixed. In the present study, we utilized a physiological correlate of cognitive effort never before used in the masked-priming LDT, pupil size, to replicate and extend behavioral demonstrations of inhibitory effects (i.e., Nakayama, Sears, & Lupker, Journal of Experimental Psychology: Human Perception and Performance, 34, 1236–1260, 2008, Exp. 1). Previous research had suggested that pupil size is a reliable indicator of cognitive load, making it a promising index of lexical inhibition. Our pupillometric data replicated and extended previous behavioral findings, in that inhibition was obtained for orthographically similar word prime–target pairs. However, our response time data provided only a partial replication of Nakayama et al. Journal of Experimental Psychology: Human Perception and Performance, 34, 1236–1260, 2008. These results provide converging lines of evidence that inhibition operates in word recognition and that pupillometry is a useful addition to word recognition researchers’ toolbox.
