---
title: "A beta way: A tutorial on Bayesian beta regression for psychological research"
date: 2026-06-11

author:
  - name: Jason Geller
    affiliation: Boston College
  - name: Robert Kubinec
    affiliation: Texas A&M University
  - name: Chelsea Parlett
    affiliation: Canva
  - name: Matti Vuorre
    affiliation: Tilburg University

categories:
  - beta regression
  - beta distribution
  - R tutorial
  - psychology
  - learning and memory

pub-info:
  reference: '<strong>Geller, J.</strong>, Kubinec, R., Parlett, C., & Vuorre, M. (2026). A beta way: A tutorial on Bayesian beta regression for psychological research. <em>Behavioral Research Methods</em>. https://doi.org/10.31234/osf.io/d6v5t_v7'
  links:
    - name: Preprint/HTML
      url: https://jgeller112.github.io/beta_regression_tutorial/
      icon: ai ai-psyarxiv-square
    - name: GitHub
      url: https://github.com/jgeller112/beta_regression_tutorial/
      icon: fa-brands fa-github-square

doi: https://doi.org/10.31234/osf.io/d6v5t_v7
---

# Abstract

Rates, percentages, and proportions are common outcomes in psychology and the social sciences. These outcomes are often analyzed using models that assume normality, but this practice overlooks important features of the data, such as their natural bounds at 0 and 1. As a result, estimates can become distorted. In contrast, treating such outcomes as beta-distributed respects these limits and can yield more accurate estimates. Despite these advantages, the use of beta models in applied research remains limited. Our goal is to provide researchers with practical guidance for adopting beta regression models, illustrated with an example drawn from the psychological literature. We begin by introducing the beta distribution and beta regression, emphasizing key components and assumptions. Next, using data from a learning and memory study, we demonstrate how to fit a beta regression model in R with the Bayesian package `{brms}` and how to interpret results on the response scale using the packages `{marginaleffects}` and `{easystats}`. We also discuss model extensions, including zero-inflated, zero- and one-inflated, and ordered beta models. Basic familiarity with regression modeling and R is assumed. To promote wider adoption of these methods, we provide detailed code and materials at <https://doi.org/10.5281/zenodo.15830595>. For researchers preferring a frequentist framework, we include an appendix demonstrating equivalent analyses using `{glmmTMB}`.