---
title: "PSY504: Advanced Statistical Medthods"
subtitle:
excerpt: "Graduate-level course  taught in [Spring 2023](https://psy504-advanced-stats.netlify.app/) and [Spring 2024](https://psy504-s24-advstats.netlify.app). This course introduces graduate students to advanced statistical methods.
We discuss: 
1.Robust Methods: bootstrapping, permutation tests 
2.Missing Data 
3.Non-Gaussian statistics: poisson regression, ordinal regression 4.Beyond Null Hypothesis Significance Testing (NHST): Structural equation models, Bayesian hypothesis testing 
5.Process models: Mediation, multiple mediation, path analysis 
6.Dimension reduction: principal components analysis (PCA), clustering" 


author: "Dr. Jason Geller"
slug: class-psy-advstatistics
draft: false
tags:
  - Statistics
  - Open Materials
categories:
  - teaching
layout: single
links:
- icon: web
  icon_pack: fas
  name: website
  url: https://psy504-advanced-stats.netlify.app/

---

## About the course  

As a discipline, statistics has given profound tools to the sciences. Statistics is our way of detecting patterns in the noisy universe. Traditionally, psychologists were limited to research questions that could be answered with classical statistical analyses, but without particularly intending to do so, psychologists have found themselves at the cutting age of statistical discovery in the 20th and 21st centuries. This is because we needed to adapt our tools to meet the demands of the complex nature of the phenomena we study. This course will give you the quantitative tools to ask and answer research questions that were impossible to test as recently as a decade ago. Specifically, we will cover the following topics as stand-alone modules:

