---
title: "Intracranial EEG evidence of functional specialization for taxonomic and thematic relations"
date: 2021-04-07
author:
  - name: Melissa Thye
    affiliation: University of Edinburgh
  - name: Jason Geller
    affiliation: Rutgers University
  - name: Jerzy P Szaflarski
    affiliation: University of Alabama at Birmingham
  - name:  Daniel Mirman
    affiliartion: University of Edinburgh
categories: 
  - Intracranial EEG
  - Semantic cognition 
  - Taxonomic
  - Thematic
pub-info:
  reference: "Thye, M., <strong>Geller, J</strong>., Szaflarski, J. P., & Mirman, D. (2021). Intracranial EEG evidence of functional specialization for taxonomic and thematic relations. <em>Cortex<em>, 140, 40–50. https://doi.org/10.1016/j.cortex.2021.03.018"
  links:
    - name: Final version
      url: https://pubmed.ncbi.nlm.nih.gov/33933929
      icon: fa-solid fa-scroll
    - name: OSF
      url: https://osf.io/xtfah/
      icon: ai ai-osf-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1016/j.cortex.2021.03.01
      icon: ai ai-zotero-square
doi:  https://doi.org/10.1016/j.cortex.2021.03.01
---

## Abstract

The dual-hub account posits that the neural organization of semantic knowledge is segregated by the type of semantic relation with anterior temporal lobe (ATL) specializing for taxonomic relations and inferior parietal lobule (IPL) for thematic relations. This study critically examined this account by recording intracranial EEG from an array of depth electrodes within ATL, IPL, and two regions within the semantic control network, inferior frontal gyrus (IFG) and posterior middle temporal gyrus (pMTG), while 17 participants with refractory epilepsy completed a semantic relatedness judgment task. We observed a significant difference between relation types in ATL and IPL approximately 600-800 ms after trial presentation, and no significant differences in IFG or pMTG. Within this time window, alpha and theta suppression indexing cognitive effort and memory retrieval was observed in ATL for taxonomic trials and in IPL for thematic trials. These results suggest taxonomic specialization in ATL and thematic specialization in IPL, consistent with the dual-hub account of semantic cognition.
