---
title: "The coding brain: P600 effects elicited by the visual programming language ScratchJr"
date: 2025-07-30
author:
  - name: Emily Nadler
    affiliation: Boston College
  - name: Jason Geller
    affiliation: Boston College
  - name: Marina U. Bers
    affiliation: Boston College
    
categories: 
  - Computer programming
  - P600
  - N400
  - ScratchJr
  - Semantic processing
pub-info:
  reference: "Nadler, E., <strong>Geller, J.</strong>, Bers, M.U.(2025). The coding brain: P600 effects elicited by the visual programming language ScratchJr. https://doi.org/10.31234/osf.io/zy8d5_v1"
  links:
    - name: Preprint
      url: https://osf.io/preprints/psyarxiv/zy8d5_v1
      icon: ai ai-psyarxiv-square
    - name: OSF
      url: https://osf.io/5ctzu/
      icon:  ai ai-osf-square
    - name: Colab
      icon: ai ai-google
      url: https://colab.research.google.com/drive/17Td09p3aZcHQDa2AgZ_fSI38cLKFfn8j#scrollTo=b6Lq89RuDhma
doi: https://doi.org/10.31234/osf.io/zy8d5_v1
---

# Abstract

In recent years, there is a growing emphasis on early childhood coding education to equip students with essential skills for a growingly technical society. While emerging research has investigated how text-based programming languages are processed in the adult brain, the neural mechanisms underlying early childhood visual programming languages like ScratchJr remain largely unexplored. This preregistered study examined the cognitive basis of ScratchJr processing, with two primary research aims: 1. Investigate whether ScratchJr elicits neural signatures comparable to natural languages and other rule-based processes (specifically N400 and semantic P600 responses) and 2. Explore how experience level with ScratchJr modulates these effects. We recorded event-related potentials (ERPs) from 40 (N = 40) adults while they completed a semantic congruency task using ScratchJr stimuli. Neural responses were analyzed in time bins associated with N400 and P600 components, and experience level with ScratchJr was included as a potential factor to modulate these results. Results revealed a P600 response to semantic violations, with no modulation by experience level. These findings contribute to growing evidence of the semantic nature of the P600 and support the notion that ScratchJr processing evokes neural mechanisms related to structured processes such as natural language.
