---
title: "Validation of the Iowa test of consonant perception"
date: 2021-10-07
author:
  - name: Jason Geller
    affiliation: University of Iowa
  - name: Ann Holmes
    affiliation: University of Iowa
  - name: Adam Schwalj
    affiliation: University of Iowa
  - name:  Joel I Berger
    affiliartion: University of Iowa
  - name: Phillip E Gander
    affiliartion: University of Iowa
  - name: Inyong Cho
    affiliartion: University of Iowa
  - name: Bob McMurray
    affiliartion: University of Iowa
  
categories: 
  - Auditory percepton
  - Speech-in-noise 
  - closed-set
  - Open-set
  - Validation
pub-info:
  reference: "Geller, J., Holmes, A., Schwalje, A., Berger, J. I., Gander, P. E., Choi, I., & McMurray, B. (2021). Validation of the Iowa test of consonant perception. The Journal of the Acoustical Society of America, 150(3), 2131. https://doi.org/10.1121/10.0006246"
  links:
    - name: Final version
      url: https://pubmed.ncbi.nlm.nih.gov/34598595/
      icon: fa-solid fa-scroll
    - name: Preprint
      url: https://osf.io/preprints/psyarxiv/wxd93
      icon: fa-solid fa-scroll
    - name: OSF
      url: https://osf.io/hycdu/
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1121/10.0006246
      icon: ai ai-zotero
doi:  https://doi.org/10.1121/10.0006246
---
## Abstract

Speech perception (especially in background noise) is a critical problem for hearing-impaired listeners and an important issue for cognitive hearing science. Despite a plethora of standardized measures, few single-word closed-set tests uniformly sample the most frequently used phonemes and use response choices that equally sample phonetic features like place and voicing. The Iowa Test of Consonant Perception (ITCP) attempts to solve this. It is a proportionally balanced phonemic word recognition task designed to assess perception of the initial consonant of monosyllabic consonant-vowel-consonant (CVC) words. The ITCP consists of 120 sampled CVC words. Words were recorded from four different talkers (two female) and uniformly sampled from all four quadrants of the vowel space to control for coarticulation. Response choices on each trial are balanced to equate difficulty and sample a single phonetic feature. This study evaluated the psychometric properties of ITCP by examining reliability (test-retest) and validity in a sample of online normal-hearing participants. Ninety-eight participants completed two sessions of the ITCP along with standardized tests of words and sentence in noise (CNC words and AzBio sentences). The ITCP showed good test-retest reliability and convergent validity with two popular tests presented in noise. All the materials to use the ITCP or to construct your own version of the ITCP are freely available [Geller, McMurray, Holmes, and Choi (2020). https://osf.io/hycdu/].
