---
title: "PSY503: Fundamentals of Statistics in Psychological Science"
subtitle:
excerpt: "Graduate-level Course course I taught in [Fall 2022](https://psy503-found-stats.netlify.app/) and [Fall 2023](https://psy503-f2023.netlify.app/). This course introduces first-year psychology students to the basics of statistics with an emphasis on the general linear model and how to use R/RStudio." 

author: "Dr. Jason Geller"
slug: class-psy-statistics-503
draft: false
tags:
  - Statistics
  - Open Materials
categories:
  - teaching
layout: single
links:
- icon: web
  icon_pack: fas
  name: Fall 2022
  url: https://psy503-found-stats.netlify.app/
  
- icon: web
  icon_pack: fas
  name: Fall 2023
  url: https://psy503-f2023.netlify.app/

---

## About the course  

This graduate-level course covers foundations of statistics in psychological research. It is required of all first-year students in the psychology Ph.D. program. The purpose of this course is to introduce students to statistics with an emphasis on modeling. We cover many of the most widely applied data analysis models in psychology. We focus on data visualization, effect size estimation and interpretation, and using statistical analysis to inform scientific research questions. We develop practical skills related to data management, reproducibility, and statistical programming through the use of R, R Markdown/Quarto, and Github.

I place a strong emphasis on practical application. I believe you are more likely to learn and readily use these analyses in the future if you do them at least once now. Every Wednesday there will be a lab going over the material covered that week. The lab assignments will help you build a personal library of example statistical scripts that you will hopefully find useful for years into the future. These lab assignments will be due at the end of the week.


