---
title: "Research Methods in Cognitive Science"
subtitle:
excerpt: "[Upper-level course](https://cogscimethods.netlify.app/) I taught in Fall 2021. This course examined the basics of research as well as the different methods cognitive scientists use to examine the mind/brain. There was a focus on replication and open science and the class culminated in a final PscyhoPy project that had to run online." 
date: 2022-01-23
author: "Jason Geller"
slug: class-cogsci-researchmethods
alias:
  - /project/tidy-tuesday-alt-text/
draft: false
tags:
  - Cog Sci
  - Open Materials
  - Accessibility
categories:
  - teaching
  - online
  - 
layout: single
links:
- icon: web
  icon_pack: fas
  name: website
  url: https://cogscimethods.netlify.app/
- icon: comment
  icon_pack: fas
  name: materials
  url: https://osf.io/ncxwv/

---

## About the course  

The aim for this course is to provide students with the necessary foundation to think critically about researchin cognitive science.  The course reviews the scientific method and considers the strengths and weaknesses ofa range of approaches, such as laboratory experimentation, neuroscience methods, and online data collection.Students will be introduced to statistical reasoning in science, including a basic overview of common statistical techniques.  We will also discuss principles for the ethical conduct of research both in the laboratory and online.This course will include traditional lectures, in-class activities, and special presentations by cognitive scientistsat  Rutgers  and  other  universities  in  the  field.   Students  will  also  get  hands-on  experience  programming  and collecting their own data, which will culminate in a paper and presentation. This course counts for 3 credits.



