---
title: "A Distributional Response Time Analysis of the Perceptual Disfluency Effect"
date: 2025-10-04
author:
  - name: Jason Geller
    affiliation: Boston College
  - name: Pablo Gomez
    affiliation: Skidmore College
  - name: Erin Buchanan
    affiliation: Harrisburg University of Science and Technology
  - name: Dominique Makowski  
    affiliation: University of Sussex
    
categories: 
  - Disfluency
  - LDT
  - DDM
  - ex-Gaussian
  - Distributional analyses
  - Word recognition
pub-info:
  reference: "<strong>Geller, J.</strong>, Gomez, P., Buchanan, E., & Makowski, D. (2025).A distributional response time analysis of the perceptual disfluency effect.<em> Journal of Cognition</em>, 8(1): 50, pp.1-26. DOI:https://journalofcognition.org/articles/10.5334/joc.469"
  links:
    - name: Paper
      icon: fa-solid fa-scroll
      url: https://journalofcognition.org/articles/10.5334/joc.469
    - name: Preprint
      url: https://osf.io/preprints/psyarxiv/sae23_v4
      icon: ai ai-psyarxiv-square
    - name: OSF
      url: https://osf.io/6sy7k/
      icon:  ai ai-osf-square
    - name: Github
      url: https://github.com/jgeller112/Disfluency_Ms
      icon: fa-brands fa-github-square
doi: https://doi.org/10.31234/osf.io/sae23_v5
---

# Abstract

Perceptual disfluency, induced by blurring or difficult-to-read typefaces, can sometimes enhance memory retention, but the underlying mechanisms remain unclear. To investigate this effect, we manipulated blurring levels (clear, low blur, high blur) during encoding and assessed recognition performance in a surprise memory test. In Experiments 1A and 1B, response latencies from a lexical decision task were analyzed using ex-Gaussian distribution modeling and drift diffusion modeling. Results showed that blurring differentially influenced parameters of the model, with high blur affecting both early and late-stage processes, while low blur primarily influenced early-stage processes. Recognition test results further revealed that high blur words were remembered better than both clear and low blurred words. Experiment 2 employed a semantic categorization task with word frequency manipulation to further examine the locus of the perceptual disfluency effect. Similar to Experiments 1A and 1B, high blur influenced both early and late-stage processes, while low blur primarily affected early-stage processes. Low-frequency words exhibited greater shifting and skewing in distributional parameters, yet only high-frequency, highly blurred words demonstrated an enhanced memory effect. These findings suggest that both early and late cognitive processes contribute to the mnemonic benefits associated with perceptual disfluency. Overall, this study demonstrates that distributional and computational analyses provide powerful tools for dissecting encoding mechanisms and their effects on memory, offering valuable insights into models of perceptual disfluency.
