---
title: "Pupillometry reveals a more sustained pattern of effortful listening in older adults"
date: 2020-07-10
author:
  - name: Ronan McFarrigle
  - name: Sarah Knight
  - name: Lyndon Rakusen 
  - name: Jason Geller
  - name: Sven Mattys
categories: 
  - Pupil
  - Effort
  - Speech
  - Age
  - Fatigue 
pub-info:
  reference: "McGarrigle, R., Knight, S., Rakusen, L., <strong>Geller, J</strong>., & Mattys, S. (2021). Older adults show a more sustained pattern of effortful listening than young adults.<em> Psychology and aging</em>, 36(4), 504–519. https://doi.org/10.1037/pag0000587"
  links:
    - name: Final version
      url: https://pubmed.ncbi.nlm.nih.gov/34014746/
      icon: fa-solid fa-scroll
    - name: OSF
      url: https://osf.io/m42wq/
      icon: ai ai-osf-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1037/pag0000587
      icon: ai ai-zotero-square
doi: https://doi.org/10.1037/pag0000587
---

## Abstract

Listening to speech in adverse conditions can be challenging and effortful, especially for older adults. This study examined age-related differences in effortful listening by recording changes in the task-evoked pupil response (TEPR; a physiological marker of listening effort) both at the level of sentence processing and over the entire course of a listening task. A total of 65 (32 young adults, 33 older adults) participants performed a speech recognition task in the presence of a competing talker, while moment-to-moment changes in pupil size were continuously monitored. Participants were also administered the Vanderbilt Fatigue Scale, a questionnaire assessing daily life listening-related fatigue within four domains (social, cognitive, emotional, physical). Normalized TEPRs were overall larger and more steeply rising and falling around the peak in the older versus the young adult group during sentence processing. Additionally, mean TEPRs over the course of the listening task were more stable in the older versus the young adult group, consistent with a more sustained recruitment of compensatory attentional resources to maintain task performance. No age-related differences were found in terms of total daily life listening-related fatigue; however, older adults reported higher scores than young adults within the social domain. Overall, this study provides evidence for qualitatively distinct patterns of physiological arousal between young and older adults consistent with age-related upregulation in resource allocation during listening. A more detailed understanding of age-related changes in the subjective and physiological mechanisms that underlie effortful listening will ultimately help to address complex communication needs in aging listeners.
